"""Phase 11: generate the four ablation configs and the fairness report."""

from __future__ import annotations

import json
import sys
from pathlib import Path

WORK = Path("${PRIVATE_WORK_ROOT}/CancerLncAtlas/rbp_encode_v33_20260921_r1")
sys.path.insert(0, str(WORK / "code"))

from cc_hhgt.v32.rbp_evidence_config import (  # noqa: E402
    ABLATION_MODES,
    assert_fair_comparison,
    config_to_yaml_block,
    resolve_mode,
)

CFG_DIR = WORK / "code" / "config" / "rbp_ablation"
CFG_DIR.mkdir(parents=True, exist_ok=True)
MANIFESTS = WORK / "manifests"

configs = [resolve_mode(mode) for mode in ABLATION_MODES]

print("=== fairness check ===")
report = assert_fair_comparison(configs)
print(f"    status  : {report['status']}")
print(f"    baseline: {report['baseline']}")
print(f"    modes   : {report['modes']}")

print("\n=== switch matrix ===")
keys = sorted(configs[0].switch_dict())
header = "  " + f"{'switch':38s}" + "".join(f"{m.split('_')[0]:>6s}" for m in ABLATION_MODES)
print(header)
for key in keys:
    row = f"  {key:38s}" + "".join(
        f"{('T' if c.switch_dict()[key] else '.'):>6s}" for c in configs
    )
    print(row)

print("\n=== writing configs ===")
for config in configs:
    path = CFG_DIR / f"{config.mode}.yaml"
    body = (
        "# Generated by phase11_generate_ablations.py -- do not hand-edit.\n"
        "# The four modes differ ONLY on the rbp_evidence switches; every fairness\n"
        "# axis is identical by construction and is re-checked at load time.\n"
        + config_to_yaml_block(config)
    )
    path.write_text(body, encoding="utf-8")
    print(f"    {path}")

(MANIFESTS / "RBP_ABLATION_FAIRNESS.json").write_text(
    json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
)
print(f"\nwritten: {MANIFESTS / 'RBP_ABLATION_FAIRNESS.json'}")

print("\n=== frozen axes shared by all four modes ===")
for key, value in report["frozen_axes"].items():
    print(f"    {key:32s} {value}")
