#!/usr/bin/env python3
"""Independent structural audit for the fresh V3.2 CNV-only OOF head."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd


TCGA_CANCERS = (
    "ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "DLBC", "ESCA",
    "GBM", "HNSC", "KICH", "KIRC", "KIRP", "LAML", "LGG", "LIHC",
    "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ",
    "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS", "UVM",
)

EXPECTED_PREDICTION_COLUMNS = {
    "cancer_id", "lncrna_id", "pathway_id", "cnv_probability", "cnv_available",
    "cnv_unavailable_reason", "model_version",
    "checkpoint_sha256",
}
FORBIDDEN_TOKENS = ("mutation", "mut_", "mutational")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    root = Path(args.root).resolve()
    report_path = Path(args.output).resolve()
    if report_path.exists():
        raise RuntimeError(f"refuse output reuse: {report_path}")

    manifest_path = root / "OOF_MANIFEST.json"
    metrics_path = root / "METRICS.json"
    if not manifest_path.is_file() or not metrics_path.is_file():
        raise RuntimeError("missing formal OOF manifest or metrics")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    if manifest.get("status") != "SUCCESS":
        raise RuntimeError(f"OOF manifest is not SUCCESS: {manifest.get('status')}")
    if manifest.get("cnv_only") is not True or manifest.get("mutation_features_used") is not False:
        raise RuntimeError("CNV-only contract is not explicit in OOF manifest")
    if manifest.get("old_checkpoint_loaded") is not False or manifest.get("old_predictions_used") is not False:
        raise RuntimeError("old checkpoint/prediction reuse flag is not false")
    if manifest.get("checkpoint_count") != 5:
        raise RuntimeError(f"expected 5 checkpoints, got {manifest.get('checkpoint_count')}")
    before = manifest.get("core_parameters_before_sha256")
    after = manifest.get("core_parameters_after_sha256")
    if not isinstance(before, dict) or before != after:
        raise RuntimeError("frozen core hash changed or is missing")

    checkpoint_records = manifest.get("checkpoints", [])
    if len(checkpoint_records) != 5:
        raise RuntimeError("checkpoint record count is not five")
    checkpoint_audit = []
    for record in checkpoint_records:
        path = Path(str(record["path"])).resolve()
        if not path.is_file():
            raise RuntimeError(f"missing checkpoint: {path}")
        actual = sha256(path)
        if actual != record.get("sha256"):
            raise RuntimeError(f"checkpoint hash mismatch: {path}")
        import torch
        # These checkpoints were generated by the fresh CNV-only runner in
        # this same immutable output root.  The explicit flag is required by
        # PyTorch >=2.6, whose default weights_only=True rejects the numpy
        # metadata stored in our auditable checkpoint envelope.
        payload = torch.load(path, map_location="cpu", weights_only=False)
        if payload.get("modality") != "cnv" or payload.get("old_checkpoint_loaded") is not False:
            raise RuntimeError(f"checkpoint contract violation: {path}")
        if payload.get("old_predictions_used") is not False:
            raise RuntimeError(f"old prediction flag set: {path}")
        checkpoint_audit.append({"fold": int(record["fold"]), "path": str(path), "sha256": actual})

    prediction_root = root / ("predictions" if (root / "predictions").is_dir() else "cnv_oof_predictions")
    prediction_files = sorted(prediction_root.glob("patient_fold=*/cancer=*.parquet"))
    if len(prediction_files) != 165:
        raise RuntimeError(f"expected 165 prediction files, got {len(prediction_files)}")
    seen = set()
    prediction_audit = []
    for path in prediction_files:
        fold = int(path.parent.name.split("=", 1)[1])
        cancer = path.stem.split("=", 1)[1]
        key = (fold, cancer)
        if key in seen:
            raise RuntimeError(f"duplicate prediction key: {key}")
        seen.add(key)
        frame = pd.read_parquet(path)
        if not EXPECTED_PREDICTION_COLUMNS.issubset(frame.columns):
            raise RuntimeError(f"prediction schema mismatch: {path}")
        if len(frame) != 100_000:
            raise RuntimeError(f"expected 100000 rows in {path}, got {len(frame)}")
        if frame.cancer_id.nunique() != 1 or str(frame.cancer_id.iloc[0]).upper() != cancer:
            raise RuntimeError(f"cancer scope mismatch: {path}")
        fold_column = "patient_fold" if "patient_fold" in frame.columns else "fold_id"
        if "training_run_id" not in frame.columns and "run_id" not in frame.columns:
            raise RuntimeError(f"missing run identifier: {path}")
        if frame[fold_column].nunique() != 1 or int(frame[fold_column].iloc[0]) != fold:
            raise RuntimeError(f"fold scope mismatch: {path}")
        for column in frame.columns:
            if any(token in column.lower() for token in FORBIDDEN_TOKENS):
                raise RuntimeError(f"mutation feature leaked into prediction output: {path}:{column}")
        available = frame.cnv_available.astype(bool).to_numpy()
        probability = pd.to_numeric(frame.cnv_probability, errors="coerce").to_numpy(dtype=float)
        if np.isfinite(probability[available]).sum() != int(available.sum()):
            raise RuntimeError(f"available CNV probabilities are not finite: {path}")
        if np.any((probability[available] < 0.0) | (probability[available] > 1.0)):
            raise RuntimeError(f"CNV probability out of range: {path}")
        if np.any(np.isfinite(probability[~available])):
            raise RuntimeError(f"typed-unavailable rows were encoded as zero/finite probability: {path}")
        reasons = frame.cnv_unavailable_reason.astype(str).to_numpy()
        if np.any(reasons[available] != ""):
            raise RuntimeError(f"available rows carry unavailable reason: {path}")
        prediction_audit.append({
            "fold": fold,
            "cancer_id": cancer,
            "rows": int(len(frame)),
            "available": int(available.sum()),
            "typed_unavailable": int((~available).sum()),
            "sha256": sha256(path),
        })
    expected_keys = {(fold, cancer) for fold in range(5) for cancer in TCGA_CANCERS}
    if seen != expected_keys:
        raise RuntimeError("prediction coverage is not exactly 5 folds x 33 cancers")
    if not isinstance(metrics.get("records"), list) or not metrics["records"]:
        raise RuntimeError("missing per-fold/per-cancer metrics")
    if not isinstance(metrics.get("global"), dict):
        raise RuntimeError("missing global metrics")

    report = {
        "format": "CC_HHGT_V3_2_CNV_HEAD_OOF_INDEPENDENT_AUDIT_V1",
        "status": "PASS",
        "oof_manifest_sha256": sha256(manifest_path),
        "metrics_sha256": sha256(metrics_path),
        "checkpoint_count": len(checkpoint_audit),
        "prediction_file_count": len(prediction_audit),
        "cancer_count": len(TCGA_CANCERS),
        "fold_count": 5,
        "checkpoint_audit": checkpoint_audit,
        "prediction_audit": prediction_audit,
        "cnv_only": True,
        "mutation_features_used": False,
        "old_checkpoint_loaded": False,
        "old_predictions_used": False,
        "typed_unavailable_never_zero": True,
        "core_hashes_unchanged": True,
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"status": "PASS", "checkpoints": 5, "prediction_files": 165, "output": str(report_path)}))


if __name__ == "__main__":
    main()
